spring:
  application:
    name: Exchange_Student_Project

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/global_db
    username: exchange_slot
    password: exchangeslot123
    hikari:
      maximum-pool-size: 50
      minimum-idle: 10
      idle-timeout: 120000
      connection-timeout: 30000
      max-lifetime: 1800000
      auto-commit: true

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        globally_quoted_identifiers: true

  cache:
    type: redis

  data:
    redis:
      host: localhost
      port: 6379

  mail:
    host: smtp.gmail.com
    port: 587
    username: "notificationsystem017@gmail.com"
    password: "lfwggxaeufcswaut"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
